version: 2

container: &container
  working_directory: ~/app
  docker:
    - image: cypress/base:12.6.0
      environment:
        TERM: xterm

jobs:
  build-test:
    <<: *container
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install
      
      - run:
          name: Build app
          command: yarn build

      - run:
          name: Start app
          command: yarn dev
          background: true
      
      - run:
          command: yarn cypress:install

      - run:
          name: Run cypress test
          command: yarn test:wait

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  
  deploy-prd:
    <<: *container
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - run:
          name: Deploy
          command: ./deploy.sh production

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  test-deploy:
    jobs:
      - build-test
      - deploy-prd:
          requires:
            - build-test
          # filters:
          #   branches:
          #     only: master
